#!/usr/bin/env python3
"""
Camera calibration tool for the Pi Camera Module 3.

Captures frames from the camera topic, detects a checkerboard pattern,
and computes camera intrinsics using OpenCV. Saves results in the format
expected by the camera driver's CameraInfo publisher.

Usage:
  ros2 run pi_camera_driver calibrate_camera -- --rows 7 --cols 9 --square-size 0.025

Prerequisites:
  - Camera node must be running with publish_raw:=true
  - A printed checkerboard (default: 9x7 inner corners, 25mm squares)
"""

import argparse
import sys
import time

import cv2
import numpy as np
import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, QoSReliabilityPolicy, QoSHistoryPolicy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge

FAST_QOS = QoSProfile(
    reliability=QoSReliabilityPolicy.BEST_EFFORT,
    history=QoSHistoryPolicy.KEEP_LAST,
    depth=1,
)

DEFAULT_OUTPUT = '/home/pi/ros2_ws/src/delivery_robot/delivery_robot_bringup/config/camera_calibration.yaml'


class CalibrationNode(Node):
    def __init__(self, rows, cols, square_size, num_frames, output_path):
        super().__init__('camera_calibrator')
        self.rows = rows
        self.cols = cols
        self.square_size = square_size
        self.num_frames = num_frames
        self.output_path = output_path

        self.bridge = CvBridge()
        self.obj_points = []
        self.img_points = []
        self.image_size = None
        self.last_capture_time = 0.0
        self.capture_interval = 1.0  # seconds between captures

        objp = np.zeros((rows * cols, 3), np.float32)
        objp[:, :2] = np.mgrid[0:cols, 0:rows].T.reshape(-1, 2) * square_size
        self.objp_template = objp

        self.sub = self.create_subscription(
            Image, 'camera/image_raw', self._image_cb, FAST_QOS
        )

        self.get_logger().info(
            f'Calibration started: {cols}x{rows} checkerboard, {square_size*1000:.1f}mm squares'
        )
        self.get_logger().info(
            f'Collecting {num_frames} frames. Move the checkerboard slowly...'
        )

    def _image_cb(self, msg):
        now = time.time()
        if now - self.last_capture_time < self.capture_interval:
            return

        frame = self.bridge.imgmsg_to_cv2(msg, desired_encoding='bgr8')
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        self.image_size = gray.shape[::-1]

        found, corners = cv2.findChessboardCorners(
            gray, (self.cols, self.rows), None
        )

        if found:
            criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
            corners_refined = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)

            self.obj_points.append(self.objp_template)
            self.img_points.append(corners_refined)
            self.last_capture_time = now

            n = len(self.obj_points)
            self.get_logger().info(f'Captured frame {n}/{self.num_frames}')

            if n >= self.num_frames:
                self._run_calibration()

    def _run_calibration(self):
        self.get_logger().info('Running calibration...')

        ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(
            self.obj_points, self.img_points, self.image_size, None, None
        )

        self.get_logger().info(f'Calibration RMS reprojection error: {ret:.4f}')
        self.get_logger().info(f'Camera matrix:\n{mtx}')
        self.get_logger().info(f'Distortion coefficients: {dist.ravel()}')

        self._save_calibration(mtx, dist)
        self.get_logger().info(f'Calibration saved to: {self.output_path}')
        self.get_logger().info('You can now restart the camera node to use the new calibration.')

        raise SystemExit(0)

    def _save_calibration(self, mtx, dist):
        w, h = self.image_size
        fx, fy = mtx[0, 0], mtx[1, 1]
        cx, cy = mtx[0, 2], mtx[1, 2]
        d = dist.ravel()

        # Projection matrix (for monocular, P = [K | 0])
        lines = [
            f'# Camera calibration for Pi Camera Module 3 (IMX708) at {w}x{h}',
            f'# Generated by calibrate_camera on {time.strftime("%Y-%m-%d %H:%M:%S")}',
            f'# RMS reprojection error: {cv2.calibrateCamera(self.obj_points, self.img_points, self.image_size, mtx, dist)[0]:.4f}',
            '',
            f'image_width: {w}',
            f'image_height: {h}',
            '',
            'camera_matrix:',
            '  rows: 3',
            '  cols: 3',
            f'  data: [{fx}, 0.0, {cx},',
            f'         0.0, {fy}, {cy},',
            '         0.0, 0.0, 1.0]',
            '',
            'distortion_model: plumb_bob',
            'distortion_coefficients:',
            '  rows: 1',
            f'  cols: {len(d)}',
            f'  data: [{", ".join(f"{v:.6f}" for v in d)}]',
            '',
            'rectification_matrix:',
            '  rows: 3',
            '  cols: 3',
            '  data: [1.0, 0.0, 0.0,',
            '         0.0, 1.0, 0.0,',
            '         0.0, 0.0, 1.0]',
            '',
            'projection_matrix:',
            '  rows: 3',
            '  cols: 4',
            f'  data: [{fx}, 0.0, {cx}, 0.0,',
            f'         0.0, {fy}, {cy}, 0.0,',
            '         0.0, 0.0, 1.0, 0.0]',
        ]

        with open(self.output_path, 'w') as f:
            f.write('\n'.join(lines) + '\n')


def main():
    parser = argparse.ArgumentParser(description='Camera calibration for Pi Camera Module 3')
    parser.add_argument('--rows', type=int, default=7, help='Inner corner rows in checkerboard')
    parser.add_argument('--cols', type=int, default=9, help='Inner corner columns in checkerboard')
    parser.add_argument('--square-size', type=float, default=0.025, help='Square size in meters')
    parser.add_argument('--num-frames', type=int, default=20, help='Number of frames to capture')
    parser.add_argument('--output', type=str, default=DEFAULT_OUTPUT, help='Output YAML path')

    # ROS2 may pass extra args; filter them
    argv = sys.argv[1:]
    if '--' in argv:
        argv = argv[argv.index('--') + 1:]
    args = parser.parse_args(argv)

    rclpy.init()
    node = CalibrationNode(args.rows, args.cols, args.square_size, args.num_frames, args.output)
    try:
        rclpy.spin(node)
    except SystemExit:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
